### PR TITLE
add skip method

### PR DESCRIPTION
**Pull request by ArnabXD**

### CODE REVIEW

**Comment by rojserbest** [comment]
Do you know you just duplicated the stop function but renamed it to skip?

**Comment by ArnabXD** [comment]
I see, I had some misunderstanding about `stream.finish()`. But `Stream.stop()` doesn't emit the `'finish'` event either ([tgcalls ref](https://github.com/tgcallsjs/tgcalls/blob/8c2eebed1eae2c43ec4de31767a6fc25edcbffe8/src/stream.ts#L88)). I understand that my suggestion maybe not necessary to `gram-tgcalls` only if we emit finish event manually. So shouldn't we add skip like this ->
```js
    skip(chatId: number): boolean | null {
        const connection = this.#connections.get(chatId);

        if (connection) {
            if (!connection.stream.finished) {
                connection.stream.finish();
                connestion.stream.emit('finish')
                return true;
            }

            return false;
        }

        return null;
    }
```

**Comment by rojserbest** [comment]
There's (a PR)[https://github.com/tgcallsjs/tgcalls/pull/6] on the tgcalls repo to make `stop` function emit `finish`.

We simply wait for @AndrewLaneX to merge it, and I will just update the required tgcalls version instead of making the lib a bloat.

Meanwhile, you can install a version of tgcalls which emits `finish` in `stop` function with: `npm i callsmusic/tgcalls`.

**Comment by AndrewLaneX** [comment]
> We simply wait for @AndrewLaneX to merge it, and I will just update the required tgcalls version instead of making the lib a bloat.

Sorry for the delay, I merged the PR.

**Pull request closed without merging**
